# Generated by Django 3.0.8 on 2020-09-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=141)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thispublisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thispost', to='network.Post')),
                ('fk_userliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisuserliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisfollowed', to=settings.AUTH_USER_MODEL)),
                ('fk_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisfollower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
