# Generated by Django 3.0.8 on 2020-09-29 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_likes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(141)]),
        ),
    ]
