# Generated by Django 3.0.8 on 2020-09-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200930_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(),
        ),
    ]
