# Generated by Django 3.0.8 on 2020-10-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200930_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='islike',
            field=models.BooleanField(null=True),
        ),
    ]
