# Generated by Django 3.0.8 on 2020-10-02 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201001_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thispost', to='network.Post')),
                ('fk_userliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisuserliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
