# Generated by Django 3.0.8 on 2020-10-02 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201002_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('fk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thispost', to='network.Post')),
                ('fk_userliked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thisuserliked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
