# Generated by Django 3.0.8 on 2020-10-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201010_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
