# Generated by Django 3.0.8 on 2020-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='No image', max_length=200),
        ),
    ]
