# Generated by Django 3.0.8 on 2020-10-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201020_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='avatar.png', max_length=200),
        ),
    ]
